apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Nginx ingress controller should handle this Ingress

spec:
  rules:                                  # Routing rules for this Ingress
  - host: {{ .Values.host }}
    http:
      paths:                              # Routing paths for this Ingress
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 80                  # The port on the Service that this Ingress will route traffic to
