apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-test-connection
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-test-connection
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date;curl http://10.96.1.1/;
          restartPolicy: OnFailure