apiVersion: batch/v1
kind: Job
metadata:
  name: job-curl-nodeport
spec:
  template:
    spec:
      containers:
      - name: job-curl-nodeport
        image: curlimages/curl:latest
        command: ['sh', '-c', 'curl http://34.68.63.220:80/']
      restartPolicy: OnFailure
