apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
          name: apache-http

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: apache
  ports:
  - port: 80
    targetPort: apache-http
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  clusterIP: 10.96.1.1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: apache-http
  selector:
    app: apache
  type: ClusterIP
